repos:
  - repo: local
    hooks:
      - id: validate-lfs
        name: Validate LFS tracking
        entry: .github/scripts/validate-lfs-track.py
        language: python
        pass_filenames: false  # Don’t run this script for each file — just run it once
